import Head from 'next/head'

import HeroBanner from "../components/HeroBanner";
import AboutUs from "../components/AboutUs";
import FAQ from "../components/FAQ";
import Prices from "../components/Prices";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>RockSchool</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeroBanner />
        <AboutUs />
        <FAQ />
        <Prices />
        <Contact />
      </main>
    </div>
  )
}
